package Code.reflect;

import java.lang.reflect.Method;

/**
 * @作者：玉蘅
 * @项目名称：codeAndPractice
 * @包名：Code.reflect
 * @文件名称：BridgeMethodExample
 * @代码功能：
 * @时间：2023/10/06/15:36
 */
public class BridgeMethodExample {
    public static void main(String[] args) throws NoSuchMethodException {
        Class<?> clazz = MyClass.class;
        Method[] methods = clazz.getDeclaredMethods();
        for (Method method : methods) {
            System.out.println(method + "==>" + method.isBridge());
        }
    }
}

class MyParentClass<T> {
    public void print(T value) {
        System.out.println(value);
    }
}

class MyClass extends MyParentClass<String> {
    // This is a bridge method generated by the compiler
    @Override
    public void print(String value) {
        super.print(value);
    }
}

